### ISSUE TITLE
Hearthstone and Windows Update doesn't cached

### ISSUE THREAD

**Issue by adamradocz** [steamcache/generic#47]
Hi,

It seems the the generic steamcache don't work. It doesn't cache the Hearthstone nor the Windows Update.
I use these settings:

```
version: '3'
services:

  steamcache:
    image: steamcache/generic
    container_name: steamcache
    restart: always
    volumes:
      - /cache/data:/data/cache
    network_mode: bridge
    ports:
      - "81:80"
    environment:
      - CACHE_MEM_SIZE=500m
      - CACHE_DISK_SIZE=100g
      - CACHE_MAX_AGE=14d
  
  steamcache-dns:
    image: steamcache/steamcache-dns
    container_name: steamcache-dns
    depends_on:
      - steamcache
    restart: always
    network_mode: bridge
    ports:
      - "54:53/udp"
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.0.100
      - UPSTREAM_DNS=1.1.1.1

  sniproxy:
    image: steamcache/sniproxy
    container_name: sniproxy
    depends_on:
      - steamcache
    restart: always
    network_mode: bridge
    ports:
      - "444:443"

```

The log shows:
```
Checking permissions (This may take a long time if the permissions are incorrect on large caches)...
Done. Starting caching server.
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
```
