### ISSUE TITLE
Provide a docker-compose.yml for running the complete stack

### ISSUE THREAD

**Issue by GotenXiao** [steamcache/generic#6]

**Comment by pyro2927** [comment]
I'm using one like this:

```yaml
version: '2'
services:
  lancache:
    image: 'steamcache/generic:latest'
    ports:
      - "80:80"
  lancache-dns:
    image: 'steamcache/steamcache-dns:latest'
    ports:
      - "53:53/udp"
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.1.100
```
